### ISSUE TITLE
Compilation error on jvmci-0.59

### ISSUE THREAD

**Issue by hlolli** [graalvm/graal-jvmci-8#4]
It seems that the compiler is complaining about https://github.com/graalvm/graal-jvmci-8/blob/91d33c78e9378a6c2fe801a9f3acb0cf7d27c1bd/src/share/vm/jvmci/jvmciCompilerToVM.cpp#L2195-L2196

```
g++ -DLINUX -D_GNU_SOURCE -DAMD64 -DPRODUCT -I. -I/build/source/src/share/vm/prims -I/build/source/src/share/vm -I/build/source/src/share/vm/precompiled -I/build/source/src/cpu/x86/vm -I/build/source/src/os_cpu/linux_x86/vm -I/build/source/src/os/linux/vm -I/build/source/src/os/posix/vm -I../generated -I/build/source/src/../mxbuild/jvmci/jdk.vm.ci.hotspot/src_gen/hotspot -I/build/mxbuild/jvmci/jvmci/jdk.vm.ci.hotspot/src_gen/hotspot -DHOTSPOT_RELEASE_VERSION="\"25.202-bga-jvmci-0.59\"" -DHOTSPOT_BUILD_TARGET="\"product\"" -DHOTSPOT_BUILD_USER="\"nixbld\"" -DHOTSPOT_LIB_ARCH=\"amd64\" -DHOTSPOT_VM_DISTRO="\"OpenJDK\""  -DTARGET_OS_FAMILY_linux -DTARGET_ARCH_x86 -DTARGET_ARCH_MODEL_x86_64 -DTARGET_OS_ARCH_linux_x86 -DTARGET_OS_ARCH_MODEL_linux_x86_64 -DTARGET_COMPILER_gcc -DCOMPILER2 -DCOMPILER1 -fPIC -fno-rtti -fno-exceptions -D_REENTRANT -fcheck-new -fvisibility=hidden -m64  -pipe -std=gnu++98 -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-strict-aliasing  -fno-omit-frame-pointer -O3  -DVM_LITTLE_ENDIAN -D_LP64=1 -Werror -Wno-deprecated-declarations -Wpointer-arith -Wsign-compare -Wundef -Wunused-function -Wunused-value    -c -MMD -MP -MF ../generated/dependencies/jvmciRuntime.o.d -fpch-deps -o jvmciRuntime.o /build/source/src/share/vm/jvmci/jvmciRuntime.cpp
In file included from /build/source/src/share/vm/jvmci/jvmci.hpp:28:0,

                 from /build/source/src/share/vm/jvmci/jvmciRuntime.hpp:28,

                 from /build/source/src/share/vm/jvmci/jvmciCompilerToVM.cpp:36:

/build/source/src/share/vm/jvmci/jvmciCompilerToVM.cpp: In function '_jlongArray* c2v_registerNativeMethods(JNIEnv*, jobject, jclass)':

/build/source/src/share/vm/jvmci/jvmciCompilerToVM.cpp:2196:81: error: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'address {aka unsigned char*}' [-Werror=format=]

             method->name_and_sig_as_C_string(), method->native_function(), entry));

                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~       ^

/build/source/src/share/vm/jvmci/jvmciExceptions.hpp:69:63: note: in definition of macro 'JVMCI_THROW_MSG_0'

 #define JVMCI_THROW_MSG_0(name, msg) { JVMCIENV->throw_##name(msg); return 0; }

                                                               ^~~

/build/source/src/share/vm/jvmci/jvmciCompilerToVM.cpp:2196:81: error: format '%lx' expects argument of type 'long unsigned int', but argument 5 has type 'address {aka unsigned char*}' [-Werror=format=]

             method->name_and_sig_as_C_string(), method->native_function(), entry));

                                                                                 ^

/build/source/src/share/vm/jvmci/jvmciExceptions.hpp:69:63: note: in definition of macro 'JVMCI_THROW_MSG_0'

 #define JVMCI_THROW_MSG_0(name, msg) { JVMCIENV->throw_##name(msg); return 0; }

                                                               ^~~

```

**Comment by dougxc** [comment]
What version of gcc is that? Apparently it's different (most likely newer) than the one in our build system.

**Comment by hlolli** [comment]
It would be `gcc (GCC) 7.4.0`

**Comment by dougxc** [comment]
Interesting. I have gcc 8.3.1 locally and it builds without any warnings. Does `INTPTR_FORMAT` produce the same warnings? Or converting the arguments with `p2i`?

**Comment by hlolli** [comment]
I did a sed replace
're-link from " PTR_FORMAT " to " PTR_FORMAT' to 
're-link from " INTPTR_FORMAT " to " INTPTR_FORMAT'

and I got the exact same error 

```
g++ -DLINUX -D_GNU_SOURCE -DAMD64 -DPRODUCT -I. -I/build/source/src/share/vm/prims -I/build/source/src/share/vm -I/build/source/src/share/vm/precompiled -I/build/source/src/cpu/x86/vm -I/build/source/src/os_cpu/linux_x86/vm -I/build/source/src/os/linux/vm -I/build/source/src/os/posix/vm -I../generated -I/build/source/src/../mxbuild/jvmci/jdk.vm.ci.hotspot/src_gen/hotspot -I/build/mxbuild/jvmci/jvmci/jdk.vm.ci.hotspot/src_gen/hotspot -DHOTSPOT_RELEASE_VERSION="\"25.202-bga-jvmci-0.59\"" -DHOTSPOT_BUILD_TARGET="\"product\"" -DHOTSPOT_BUILD_USER="\"nixbld\"" -DHOTSPOT_LIB_ARCH=\"amd64\" -DHOTSPOT_VM_DISTRO="\"OpenJDK\""  -DTARGET_OS_FAMILY_linux -DTARGET_ARCH_x86 -DTARGET_ARCH_MODEL_x86_64 -DTARGET_OS_ARCH_linux_x86 -DTARGET_OS_ARCH_MODEL_linux_x86_64 -DTARGET_COMPILER_gcc -DCOMPILER2 -DCOMPILER1 -fPIC -fno-rtti -fno-exceptions -D_REENTRANT -fcheck-new -fvisibility=hidden -m64  -pipe -std=gnu++98 -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-strict-aliasing  -fno-omit-frame-pointer -O3  -DVM_LITTLE_ENDIAN -D_LP64=1 -Werror -Wno-deprecated-declarations -Wpointer-arith -Wsign-compare -Wundef -Wunused-function -Wunused-value    -c -MMD -MP -MF ../generated/dependencies/jvmciJavaClasses.o.d -fpch-deps -o jvmciJavaClasses.o /build/source/src/share/vm/jvmci/jvmciJavaClasses.cpp
Compiling /build/source/src/share/vm/jvmci/jvmciRuntime.cpp
rm -f jvmciRuntime.o
g++ -DLINUX -D_GNU_SOURCE -DAMD64 -DPRODUCT -I. -I/build/source/src/share/vm/prims -I/build/source/src/share/vm -I/build/source/src/share/vm/precompiled -I/build/source/src/cpu/x86/vm -I/build/source/src/os_cpu/linux_x86/vm -I/build/source/src/os/linux/vm -I/build/source/src/os/posix/vm -I../generated -I/build/source/src/../mxbuild/jvmci/jdk.vm.ci.hotspot/src_gen/hotspot -I/build/mxbuild/jvmci/jvmci/jdk.vm.ci.hotspot/src_gen/hotspot -DHOTSPOT_RELEASE_VERSION="\"25.202-bga-jvmci-0.59\"" -DHOTSPOT_BUILD_TARGET="\"product\"" -DHOTSPOT_BUILD_USER="\"nixbld\"" -DHOTSPOT_LIB_ARCH=\"amd64\" -DHOTSPOT_VM_DISTRO="\"OpenJDK\""  -DTARGET_OS_FAMILY_linux -DTARGET_ARCH_x86 -DTARGET_ARCH_MODEL_x86_64 -DTARGET_OS_ARCH_linux_x86 -DTARGET_OS_ARCH_MODEL_linux_x86_64 -DTARGET_COMPILER_gcc -DCOMPILER2 -DCOMPILER1 -fPIC -fno-rtti -fno-exceptions -D_REENTRANT -fcheck-new -fvisibility=hidden -m64  -pipe -std=gnu++98 -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-strict-aliasing  -fno-omit-frame-pointer -O3  -DVM_LITTLE_ENDIAN -D_LP64=1 -Werror -Wno-deprecated-declarations -Wpointer-arith -Wsign-compare -Wundef -Wunused-function -Wunused-value    -c -MMD -MP -MF ../generated/dependencies/jvmciRuntime.o.d -fpch-deps -o jvmciRuntime.o /build/source/src/share/vm/jvmci/jvmciRuntime.cpp
Compiling /build/source/src/share/vm/jvmci/jvmci_globals.cpp
rm -f jvmci_globals.o
In file included from /build/source/src/share/vm/jvmci/jvmci.hpp:28:0,

                 from /build/source/src/share/vm/jvmci/jvmciRuntime.hpp:28,

                 from /build/source/src/share/vm/jvmci/jvmciCompilerToVM.cpp:36:

/build/source/src/share/vm/jvmci/jvmciCompilerToVM.cpp: In function '_jlongArray* c2v_registerNativeMethods(JNIEnv*, jobject, jclass)':

/build/source/src/share/vm/jvmci/jvmciCompilerToVM.cpp:2196:81: error: format '%lx' expects argument of type 'long unsigned int', but argument 4 has type 'address {aka unsigned char*}' [-Werror=format=]

             method->name_and_sig_as_C_string(), method->native_function(), entry));

                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~       ^

/build/source/src/share/vm/jvmci/jvmciExceptions.hpp:69:63: note: in definition of macro 'JVMCI_THROW_MSG_0'

 #define JVMCI_THROW_MSG_0(name, msg) { JVMCIENV->throw_##name(msg); return 0; }

                                                               ^~~

/build/source/src/share/vm/jvmci/jvmciCompilerToVM.cpp:2196:81: error: format '%lx' expects argument of type 'long unsigned int', but argument 5 has type 'address {aka unsigned char*}' [-Werror=format=]

             method->name_and_sig_as_C_string(), method->native_function(), entry));

                                                                                 ^

/build/source/src/share/vm/jvmci/jvmciExceptions.hpp:69:63: note: in definition of macro 'JVMCI_THROW_MSG_0'

 #define JVMCI_THROW_MSG_0(name, msg) { JVMCIENV->throw_##name(msg); return 0; }

                                                               ^~~
```

OTOH sed-ing
'method->name_and_sig_as_C_string(), method->native_function(), entry'
with
'method->name_and_sig_as_C_string(), p2i(method->native_function()), p2i(entry)'

makes the whole compilation succeed!

**Comment by hlolli** [comment]
Well it didn't matter so much, as I went further into the compilation and had an error (with graal 1.0.0-rc16) 


post it here for what it's worth, I can open a ticket on oracle/graal.

```
52686 method(s) included for runtime compilation
WARNING: suspicious method reachable for runtime compilation: com.oracle.svm.core.deopt.Deoptimizer.deoptSourceFrameOperation(CodePointer, boolean, IsolateThread)
Check the complete tree of reachable methods using the option PrintRuntimeCompileMethods
Suspicious method is called from
  com.oracle.svm.core.deopt.Deoptimizer.access$000(Deoptimizer.java:146) -> com.oracle.svm.core.deopt.Deoptimizer$DeoptSourceFrameOperation.operate(Deoptimizer.java:596)
  com.oracle.svm.core.thread.VMOperation.operateUnderIndicator(VMOperation.java:149)
  com.oracle.svm.core.thread.VMOperation.execute(VMOperation.java:134)
  com.oracle.svm.core.thread.VMOperationControl$Worklist.drain(VMOperationControl.java:316)
  com.oracle.svm.core.thread.VMOperationControl.drain(VMOperationControl.java:181)
  com.oracle.svm.core.thread.VMOperationControl.enqueue(VMOperationControl.java:163)
  com.oracle.svm.core.thread.VMOperation.enqueue(VMOperation.java:99)
  com.oracle.svm.core.thread.VMOperation.enqueueBlockingNoSafepoint(VMOperation.java:125)
  com.oracle.svm.core.thread.JavaThreads.interruptVMCondVars(JavaThreads.java:517) -> com.oracle.svm.core.thread.Target_java_lang_Thread.interrupt0(JavaThreads.java:892)
  java.lang.Thread.interrupt(Thread.java:922)
  java.io.PrintStream.newLine(PrintStream.java:556)
  java.io.PrintStream.println(PrintStream.java:808)
  com.ibm.icu.impl.Trie2Writable.freeze(Trie2Writable.java:1098)
  com.ibm.icu.impl.Trie2Writable.toTrie2_32(Trie2Writable.java:998)
  com.ibm.icu.impl.Normalizer2Impl.ensureCanonIterData(Normalizer2Impl.java:655)
  com.ibm.icu.impl.UCharacterProperty$5.contains(UCharacterProperty.java:305)
  com.ibm.icu.impl.UCharacterProperty.getIntPropertyValue(UCharacterProperty.java:621)
  com.ibm.icu.lang.UCharacter.getIntPropertyValue(UCharacter.java:5683) -> com.ibm.icu.text.RuleBasedBreakIterator.getLanguageBreakEngine(RuleBasedBreakIterator.java:682)
  com.ibm.icu.text.RuleBasedBreakIterator.access$100(RuleBasedBreakIterator.java:40) -> com.ibm.icu.text.RuleBasedBreakIterator$DictionaryCache.populateDictionary(RuleBasedBreakIterator.java:1211)
  com.ibm.icu.text.RuleBasedBreakIterator$BreakCache.populateFollowing(RuleBasedBreakIterator.java:1522)
  com.ibm.icu.text.RuleBasedBreakIterator$BreakCache.populateNear(RuleBasedBreakIterator.java:1458)
  com.ibm.icu.text.RuleBasedBreakIterator.first(RuleBasedBreakIterator.java:364)
  com.ibm.icu.text.RuleBasedBreakIterator.setText(RuleBasedBreakIterator.java:647)
  com.ibm.icu.text.BreakIterator.setText(BreakIterator.java:514)
  com.oracle.truffle.js.builtins.SegmenterPrototypeBuiltins$CreateSegmentIteratorNode.execute(SegmenterPrototypeBuiltins.java:148)
  com.oracle.truffle.js.builtins.SegmenterPrototypeBuiltins$JSSegmenterSegmentNode.doSegment(SegmenterPrototypeBuiltins.java:123)
  com.oracle.truffle.js.builtins.SegmenterPrototypeBuiltinsFactory$JSSegmenterSegmentNodeGen.execute(SegmenterPrototypeBuiltinsFactory.java:164)
  com.oracle.truffle.js.nodes.control.AsyncFunctionBodyNode$AsyncFunctionRootNode.execute(AsyncFunctionBodyNode.java:95)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
  org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)

[libpolyglot:32401]     universe:   7,732.52 ms
[libpolyglot:32401]      (parse):   7,393.96 ms
[libpolyglot:32401]      compile:   7,406.62 ms
Fatal error: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: java.lang.NullPointerException
        at parsing com.oracle.svm.core.hub.DynamicHub.getMethod(DynamicHub.java:971)
        at method: Method java.lang.Class.getMethod(String, Class[])
        at org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2621)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:85)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3421)
        at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
        at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
        at com.oracle.svm.hosted.phases.HostedBytecodeParser.build(HostedGraphBuilderPhase.java:107)
        at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:838)
        at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.svm.hosted.code.CompileQueue.defaultParseFunction(CompileQueue.java:713)
        at com.oracle.svm.hosted.code.CompileQueue.doParse(CompileQueue.java:679)
        at com.oracle.svm.hosted.code.CompileQueue$ParseTask.run(CompileQueue.java:302)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:190)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:156)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1534)
        at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1509)
        at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5257)
        at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
        ... 18 more
Error: Image build request failed with exit status 1
```

**Comment by dougxc** [comment]
Yes, please open a ticket on oracle/graal.

**Comment by dougxc** [comment]
This issue should now be fixed by https://github.com/graalvm/graal-jvmci-8/commit/49b68a769ebaebaf792fc03c98b3cf8e2384813e. Please confirm and close.

**Comment by hlolli** [comment]
yes fixed long ago!
