### ISSUE TITLE
Python version error

### ISSUE THREAD

**Issue by helloguo** [graalvm/graal-jvmci-8#8]
When I run `mx --java-home ~/path/to/java/jome build`, I saw this error:
```
Traceback (most recent call last):
  File "/home/helloguo/dev/mx/mx.py", line 17180, in <module>
    main()
  File "/home/helloguo/dev/mx/mx.py", line 17065, in main
    primary = _discover_suites(primarySuiteMxDir, load=should_load_suites)
  File "/home/helloguo/dev/mx/mx.py", line 3506, in _discover_suites
    _register_visit(primary)
  File "/home/helloguo/dev/mx/mx.py", line 3504, in _register_visit
    s._load()
  File "/home/helloguo/dev/mx/mx.py", line 1604, in _load
    self._load_extensions()
  File "/home/helloguo/dev/mx/mx.py", line 2026, in _load_extensions
    mod = __import__(extensionsName)
  File "/home/helloguo/dev/graal-jvmci-8/mx.jvmci/mx_jvmci.py", line 44, in <module>
    assert sys.version_info[0] >= 3, 'Requires Python 3: ' + str(sys.version_info)
AssertionError: Requires Python 3: sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)
```

However, when I check the python version, python3 is used by default on my system (CentOS 7).
```
python --version
Python 3.6.8
```

Anyone saw this error before? And how to solve it? Thanks!

**Comment by helloguo** [comment]
When running this cmd `env MX_PYTHON=python3 mx --java-home path/to/java/home build`, it does not complain about the Python version, I saw another error instead:

```
Traceback (most recent call last):
  File "/home/helloguo/dev/mx/mx.py", line 17180, in <module>
    main()
  File "/home/helloguo/dev/mx/mx.py", line 17089, in main
    primary_suite().recursive_post_init()
  File "/home/helloguo/dev/mx/mx.py", line 2309, in recursive_post_init
    self._post_init()
  File "/home/helloguo/dev/mx/mx.py", line 2339, in _post_init
    self._post_init_finish()
  File "/home/helloguo/dev/mx/mx.py", line 1907, in _post_init_finish
    self.mx_post_parse_cmd_line(_opts)
  File "/home/helloguo/dev/graal-jvmci-8/mx.jvmci/mx_jvmci.py", line 1626, in mx_post_parse_cmd_line
    get_jvmci_bootstrap_jdk()
  File "/home/helloguo/dev/graal-jvmci-8/mx.jvmci/mx_jvmci.py", line 1531, in get_jvmci_bootstrap_jdk
    _jvmci_bootstrap_jdk = mx.get_jdk(_versionCheck, versionDescription=versionDesc, tag='default')
  File "/home/helloguo/dev/mx/mx.py", line 12163, in get_jdk
    jdk = _find_jdk(versionCheck=versionCheck, versionDescription=versionDescription)
  File "/home/helloguo/dev/mx/mx.py", line 12201, in _find_jdk
    result = _filtered_jdk_configs(candidateJdks, versionCheck, missingIsError=True, source=source)
  File "/home/helloguo/dev/mx/mx.py", line 12275, in _filtered_jdk_configs
    if not versionCheck or versionCheck(jdk.version):
  File "/home/helloguo/dev/graal-jvmci-8/mx.jvmci/mx_jvmci.py", line 1527, in _versionCheck
    return version >= _minVersion and ((not _untilVersion) or version < _untilVersion)
  File "/home/helloguo/dev/mx/mx.py", line 446, in __ge__
    return self._checked_cmp(other, lambda a, b: a >= b)
  File "/home/helloguo/dev/mx/mx.py", line 434, in _checked_cmp
    compar = self.__cmp__(other) #pylint: disable=assignment-from-no-return
  File "/home/helloguo/dev/mx/mx.py", line 12929, in __cmp__
    return compare(self.strippedParts, other.strippedParts)
  File "/home/helloguo/dev/mx/mx.py", line 430, in compare
    return (a > b) - (a < b)
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by gilles-duboscq** [comment]
i guess `path/to/java/home/bin/java -version` outputs something that the version parsing doesn't understand
